name: Generate PowerShell Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'modules/**/*.ps1'
      - 'modules/**/*.psm1'
      - 'modules/**/*.psd1'
  pull_request:
    branches:
      - main
    paths:
      - 'modules/**/*.ps1'
      - 'modules/**/*.psm1'
      - 'modules/**/*.psd1'
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache PowerShell Modules
        id: cache-modules
        uses: actions/cache@v3
        with:
          path: |
            ~\Documents\PowerShell\Modules
            C:\Users\runneradmin\Documents\PowerShell\Modules
          key: ${{ runner.os }}-pwsh-modules-${{ hashFiles('**/tcs.intune.packaging.psd1') }}
          restore-keys: |
            ${{ runner.os }}-pwsh-modules-

      - name: Install PlatyPS
        if: steps.cache-modules.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          Install-Module -Name PlatyPS -Force -Scope CurrentUser -AllowClobber

      - name: Install Required Modules
        if: steps.cache-modules.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          # Install Microsoft Graph modules
          Write-Host "Installing Microsoft Graph modules..."
          Install-Module -Name Microsoft.Graph.Authentication -Force -Scope CurrentUser -AllowClobber
          Install-Module -Name Microsoft.Graph.Devices.CorporateManagement -Force -Scope CurrentUser -AllowClobber
          Install-Module -Name Microsoft.Graph.Intune -Force -Scope CurrentUser -AllowClobber
          
          # Install custom required modules from PSGallery
          Write-Host "Installing tcs.core module..."
          Install-Module -Name tcs.core -Force -Scope CurrentUser -AllowClobber

      - name: Import and Setup Dependencies
        shell: pwsh
        run: |
          # Import PlatyPS
          Import-Module PlatyPS -Force
          
          # Import all required modules
          Write-Host "Importing tcs.core..."
          Import-Module -Name tcs.core -Force -Verbose
          
          # Verify tcs.core is loaded and show its functions
          $tcsCoreModule = Get-Module -Name tcs.core
          if ($tcsCoreModule) {
            Write-Host "tcs.core version $($tcsCoreModule.Version) loaded successfully"
            Write-Host "Exported functions: $($tcsCoreModule.ExportedFunctions.Keys -join ', ')"
          } else {
            throw "tcs.core module did not load properly"
          }
          
          # Import the main module
          Write-Host "Importing tcs.intune.packaging..."
          Import-Module .\modules\tcs.intune.packaging\tcs.intune.packaging.psd1 -Force -Verbose
          
          # Verify the module loaded
          $mainModule = Get-Module -Name tcs.intune.packaging
          if ($mainModule) {
            Write-Host "Successfully loaded tcs.intune.packaging version: $($mainModule.Version)"
            Write-Host "Exported functions count: $($mainModule.ExportedFunctions.Count)"
          } else {
            throw "Failed to load tcs.intune.packaging module"
          }

      - name: Generate Markdown Documentation
        shell: pwsh
        run: |
          # Re-import PlatyPS in this session
          Import-Module PlatyPS -Force
          
          # Re-import tcs.core
          Import-Module -Name tcs.core -Force
          
          # Create stub functions for missing tcs.core functions (for doc generation only)
          if (-not (Get-Command Get-ModuleConfig -ErrorAction SilentlyContinue)) {
            Write-Host "Creating stub Get-ModuleConfig function for documentation generation"
            function global:Get-ModuleConfig { param($CommandPath) return @{ModuleName='tcs.intune.packaging'; ModulePath=''; BasicTelemetry='False'} }
          }
          if (-not (Get-Command Invoke-TelemetryCollection -ErrorAction SilentlyContinue)) {
            Write-Host "Creating stub Invoke-TelemetryCollection function for documentation generation"
            function global:Invoke-TelemetryCollection { param([hashtable]$TelemetryArgs, [string]$Stage, [switch]$ClearTimer, [switch]$Failed, $Exception, [switch]$Minimal) }
          }
          
          # Re-import the main module in this session
          Write-Host "Importing tcs.intune.packaging in documentation generation session..."
          Import-Module .\modules\tcs.intune.packaging\tcs.intune.packaging.psd1 -Force
          
          # Verify module is loaded
          $module = Get-Module -Name tcs.intune.packaging
          if (-not $module) {
            throw "Module tcs.intune.packaging is not loaded"
          }
          Write-Host "Module loaded with $($module.ExportedFunctions.Count) functions"
          
          $moduleName = "tcs.intune.packaging"
          $docsPath = ".\docs"
          
          # Create docs directory if it doesn't exist
          if (-not (Test-Path $docsPath)) {
            New-Item -Path $docsPath -ItemType Directory -Force
          }
          
          # Generate markdown help files
          Write-Host "Generating markdown help files..."
          New-MarkdownHelp -Module $moduleName -OutputFolder $docsPath -Force
          
          # Generate module page
          Write-Host "Generating module about page..."
          New-MarkdownAboutHelp -OutputFolder $docsPath -AboutName $moduleName

      - name: Update Documentation
        shell: pwsh
        run: |
          # Re-import PlatyPS
          Import-Module PlatyPS -Force
          
          # Re-import tcs.core
          Import-Module -Name tcs.core -Force
          
          # Create stub functions for missing tcs.core functions
          if (-not (Get-Command Get-ModuleConfig -ErrorAction SilentlyContinue)) {
            function global:Get-ModuleConfig { param($CommandPath) return @{ModuleName='tcs.intune.packaging'; ModulePath=''; BasicTelemetry='False'} }
          }
          if (-not (Get-Command Invoke-TelemetryCollection -ErrorAction SilentlyContinue)) {
            function global:Invoke-TelemetryCollection { param([hashtable]$TelemetryArgs, [string]$Stage, [switch]$ClearTimer, [switch]$Failed, $Exception, [switch]$Minimal) }
          }
          
          # Re-import the main module
          Write-Host "Importing tcs.intune.packaging for update step..."
          Import-Module .\modules\tcs.intune.packaging\tcs.intune.packaging.psd1 -Force
          
          # Verify module is loaded
          $module = Get-Module -Name tcs.intune.packaging
          if (-not $module) {
            throw "Module tcs.intune.packaging is not loaded in update step"
          }
          Write-Host "Module loaded with $($module.ExportedFunctions.Count) functions"
          
          $docsPath = ".\docs"
          $moduleName = "tcs.intune.packaging"
          
          # Update existing markdown files if they exist
          if (Test-Path $docsPath) {
            Write-Host "Updating markdown help module..."
            Update-MarkdownHelpModule -Path $docsPath -RefreshModulePage
          }

      - name: Generate External Help
        shell: pwsh
        run: |
          # Re-import PlatyPS
          Import-Module PlatyPS -Force
          
          $docsPath = ".\docs"
          $modulePath = ".\modules\tcs.intune.packaging"
          $locale = "en-US"
          
          # Create locale directory in module
          $helpPath = Join-Path $modulePath $locale
          if (-not (Test-Path $helpPath)) {
            New-Item -Path $helpPath -ItemType Directory -Force
          }
          
          # Generate external help XML file
          New-ExternalHelp -Path $docsPath -OutputPath $helpPath -Force

      - name: Commit and Push Documentation
        shell: pwsh
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add docs/
          git add modules/tcs.intune.packaging/en-US/
          
          # Check if there are changes to commit
          $changes = git status --porcelain
          if ($changes) {
            git commit -m "docs: Auto-generate PowerShell documentation [skip ci]"
            git push
          } else {
            Write-Host "No documentation changes to commit"
          }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
